### PR TITLE
Make Faraday version less restrictive

### PR DESCRIPTION
**Pull request by ramontayag**
- Anything from 0.10 to < 2
- Tested 1.0.1 manually, on an application. `send_message` works.
- Based on https://github.com/lostisland/faraday/blob/master/CHANGELOG.md, no breaking changes from 0.x to 1.x
- Update bundler (development only)

### CODE REVIEW

**Comment by 4ndv** [comment]
Too risky to do it this way. But there is better one: just update spec to the more modern version and test if everything works.

**Comment by ramontayag** [comment]
How come? Wouldn't the apps themselves, with Gemfile.lock committed, be the ones to lock the Faraday version?

**Comment by ramontayag** [comment]
Or by risk do you mean breaking rubyviber without the app owner knowing? Yes, you have a point. Ok, I'll update it the gemspec.

**Comment by 4ndv** [comment]
> Or by risk do you mean breaking rubyviber without the app owner knowing? Yes, you have a point. Ok, I'll update it the gemspec.

Exactly. There is no way of knowing if there was any breaking changes in faraday, that will make rubyviber unusable, without actually testing it.

**Comment by 4ndv** [comment]
Have you tested it on faraday 1.x?

**Comment by ramontayag** [comment]
Ok @4ndv ready again

**Comment by 4ndv** [comment]
And please, change ~> 2.1 in bundler to ~> 2.0

**Comment by 4ndv** [comment]
Also, bump rubyviber version

**Comment by ramontayag** [comment]
- [x] yes tested Faraday 1.x manually, `send_message` works. Also noted this in the PR description and commit message
- [x] bundler version to ~> 2.0
- [x] bumped version to `0.3.0`

**Comment by 4ndv** [comment]
Thank you! Will push to rubygems in 10-20 minutes

**Comment by 4ndv** [comment]
Pushed to rubygems, wait until rg cache is updated and you can update your bundle

**Comment by ramontayag** [comment]
Thank you!
Ramon Tayag

**Pull request merged**
